### ISSUE TITLE
Empire AI won't build Darth_Vader_Expansion or Death_Star_II in GC

### ISSUE THREAD

**Issue by AlyMar1994** [AlyMar1994/UFoCP#11]
As title.

**Comment by AlyMar1994** [comment]
It's also of note that out of my 100+ hours in vanilla Empire at War, I've never seen the Empire AI build the Death Star I, even on hard.

I'll need to look further whether AI regarding building the Death_Star actually exists/or if it's broken or not.

**Comment by AlyMar1994** [comment]
As of 12/13/18, I can confirm that in Empire at War the AI does build the Death Star, and uses it to blow up planets (on medium difficulty).

At least I can start there as a base, to see if changes to the AI take effect.

**Comment by KadVenku** [comment]
I would assume that the AI build plan doesn't hold the proper `GameObjectType` reference for the Death Star II.

As far as Darth Vader is concerned, it would probably be simplest to just spawn the correct team via a story event as any other hero does instead of writing an appropriate build plan.

**Comment by AlyMar1994** [comment]
> As far as Darth Vader is concerned, it would probably be simplest to just spawn the correct team via a story event as any other hero does instead of writing an appropriate build plan.

I never find the simplest solutions, at least in this case, the best.

I'd consider it pretty unfair for the AI to just _get_ Vader at a certain tech level, especially since Petroglyph made him build-able for a reason (which I assume is because he's so powerful). I'll start working on it and see if I can get something done tonight.

**Comment by AlyMar1994** [comment]
So it's probable a solution has been found, at least for Darth Vader.

There exists a BuildSpaceForcesPlan.LUA AI file that seems to dictate the building of space forces (_believe it or not_). It might be possible to add Darth_Vader_Expansion to this list, so the Empire has it as a part of their build plan.

Still searching for the Death Star's original build plan.

**Comment by AlyMar1994** [comment]
As of an upcoming update for v1.5, the Empire will now construct the Death Star and Darth Vader, as it's now been added to their AI Tech plan.
