### ISSUE TITLE
Death Star II targets the moon and not the planet in Nal Hutta space

### ISSUE THREAD

**Issue by AlyMar1994** [AlyMar1994/UFoCP#23]
Lany theorizes it's because of the object hierarchy on the map. If the planet is placed first, the DS targets that.

**Comment by gruenwaldlk** [comment]
Both props probably have the `DUMMY_TACTICAL_SUPER_WEAPON_TARGET` behaviour.      
I assume that the game then just picks the first.

Fun fact: Lore-wise the behaviour even makes sense to some degree: Nal Hutta was a dump, the moon Nar Shaddaa was the important outpost

**Comment by AlyMar1994** [comment]
I've mostly forgotten about this, however visually it does seem unintentional (as the exploded asteroid field is extremely close to the fighters, DS floats upwards toward the playing field, etc).

If they both have the behavior, is it possible to blow up both objects by going in two times? I should begin testing. If that prop isn't used as a planet anywhere else and can have that tag removed, it should.

**Comment by gruenwaldlk** [comment]
> visually it does seem unintentional
It's probably a bug, but it's funny that it occurs on Nal Hutta

> If they both have the behavior, is it possible to blow up both objects by going in two times?

I would assume that the parent mode object (the planet in GC) is alredy marked as destroyed, so the Death Star probably can't target the planet again.

**Comment by AlyMar1994** [comment]
About to try and fix this bug. As a note, when you leave, the entire planet on the GC scale becomes planetary debris, and when you return to the planet, the planet itself becomes debris while the moon reforms into a moon again.

GG Petro

**Comment by AlyMar1994** [comment]
Fixed e29beda.
