### ISSUE TITLE
Canderous Assault Tank - Inaccurate Collision Mesh + Improved Shadow Mesh

### ISSUE THREAD

**Issue by ShyShallot** [AlyMar1994/UFoCP#37]
The shadow mesh on the Canderous is not accurate in most places as seen here:
Before:
![image](https://user-images.githubusercontent.com/29870626/109727899-0aa0eb00-7b6a-11eb-97bf-5e94d627a7d4.png)
![image](https://user-images.githubusercontent.com/29870626/109727943-21474200-7b6a-11eb-9704-ec449671e684.png)
And After: 
![image](https://user-images.githubusercontent.com/29870626/109727963-2ad0aa00-7b6a-11eb-9b3e-2aaf2d4c5a47.png)
![image](https://user-images.githubusercontent.com/29870626/109728015-4471f180-7b6a-11eb-8666-cf497f9307d1.png)

**Comment by ShyShallot** [comment]
Side by Side comparison of Before and After shadow mesh geometry 
![image](https://user-images.githubusercontent.com/29870626/109728288-bea27600-7b6a-11eb-806f-441141f3cf15.png)
![image](https://user-images.githubusercontent.com/29870626/109728306-c530ed80-7b6a-11eb-9c9d-b13f1c5b94ae.png)

**Comment by gruenwaldlk** [comment]
Most shadows in the base game are simplified to varying degrees for performance reasons, e.g. the missing grills on the side in this particular case.

So I'm not sure if this classifies as a bug at all.

**Comment by ShyShallot** [comment]
reasonable, wasnt really reported as a bug but a suggestion, the model also includes a fixed it hitbox also

**Comment by gruenwaldlk** [comment]
> reasonable, wasnt really reported as a bug but a suggestion, the model also includes a fixed it hitbox also

I was mostly just pointing the optimisation bit on the shadow mesh out - in the end it's up to @AlyMar1994 and where he draws the line between bug fix and enhancement/change and which one should be included in an unofficial patch project.

The hitbox and if present crusher on the other hand is definetly something that needs to be fixed.

**Comment by ShyShallot** [comment]
[UV_CANDEROUSASSAULTTANK.zip](https://github.com/AlyMar1994/UFoCP/files/6717650/UV_CANDEROUSASSAULTTANK.zip)
The Added Faces to the Shadow Mesh only really add about ~10 faces so it shouldn't have much of an impact and this also includes the fixes to the crusher and collision boxes.
